install:
	python -m pip install --upgrade pip
	pip install -r requirements.txt

ver_run:
	python dynaconf_2/example_dynaconf_2.py --env=ver

prd_run:
	python dynaconf_2/example_dynaconf_2.py --env=prd
